name: mix

on:
  workflow_dispatch:
  schedule:
    - cron: "42 9 * * *"

jobs:
  bench:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: bench

    services:
      clickhouse:
        image: postgres:17-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: 1
          otp-version: 27

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: bench-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            bench-${{ github.head_ref || github.ref }}-
            bench-refs/heads/master-

      - run: mix deps.get --only $MIX_ENV
      - run: mix compile --warnings-as-errors
      - run: mix run bench/postgres.exs
